### ISSUE TITLE
v2 theme discussion

### ISSUE THREAD

**Issue by mskelton** [Widen/jekyll-theme-guardian#12]
@dbeg mentioned in #9 about the potential to create a v2 of this theme that could provide some larger improvements to the theme.  I'm opening this issue here so we can discuss and list some of the wants and needs for a v2 of this theme.

- [ ] Header image which properly repeats
- [ ] Remove Helvetica Neue in favor of the new fonts we use
- [ ] Icons which match our brand icons
- [ ] Improved accessibility and responsiveness
- [ ] Add hash to generated filenames for proper cache busting

**Comment by dbeg** [comment]
Let's also address cache/busting during this time to ensure our stylesheet caches are busted during deploys (as I just got a cached copy and ran into some incorrect styles).
